### PR TITLE
Expose  comment_meta container

### PR DESCRIPTION
**Pull request by benada002**
What do you think about it?

### CODE REVIEW

**Comment by matepaiva** [comment]
Is this enough to make it work? So straightforward! :D

**Comment by benada002** [comment]
It looks like it. I tried it with these fields:
```php
WpGraphQLCrbContainer::register(
        Container::make('comment_meta', __('Comment Information'))
            ->add_fields(
                array(
                Field::make('text', 'crb_comment_rating', __('Comment Rating')),
                Field::make('text', 'crb_comment_additional_info', __('Additional Comment Information')),
                Field::make('select', 'crb_sc_select', __('Choose Options'))
                ->set_options(
                    array(
                    '1' => 1,
                    '2' => 2,
                    '3' => 3,
                    '4' => 4,
                    '5' => 5,
                    ) 
                ),
                Field::make('checkbox', 'sc_cable', __('checkbox'))
                    ->set_default_value('yes')
                    ->set_option_value('yes'),
                Field::make('complex', 'sc_com_options', __('Option'))
                    ->add_fields(
                        array(
                            Field::make('text', 'sc_com_options_name', __('Name'))
                                ->set_required(true),
                            Field::make('text', 'sc_com_options_test', __('Test'))
                                ->set_help_text('Beispiel: +10.00'),
                        )
                    ),
                    Field::make('media_gallery', 'crb_media_gallery', __('Media Gallery'))

                ),
            )
    );
```
They're all showing up in the GraphIQL tool.

Would prefer `$comment->comment_ID` or `$comment->databaseId` to get the comment id?

**Comment by matepaiva** [comment]
I think `databaseId` works better as wpgraphql already calls them as databaseId :)

**Comment by benada002** [comment]
That's what I thought (and used) :)

**Comment by matepaiva** [comment]
New release 0.0.4 with your contribution: https://packagist.org/packages/matepaiva/wp-graphql-crb

You are amazing! 🎉

**Comment by benada002** [comment]
I just updated and tested it again in a React app. Everything works great so far.

**Pull request merged**
